### ISSUE TITLE
Add not consumable messages to dead letter queue

### ISSUE THREAD

**Issue by lordudun** [marceljanerfont/amqppy#1]
When an exception happen if is not possible to consume the message add it to a dead letter queue

**Comment by marceljanerfont** [comment]
Try to throw the exception ```amqppy.DeadLetterMessage``` whenever you want to reject an incoming message without re-queueing. The message would be thrown to DLX if it is properly configurated.

The test of this feature is missing in amqppy, tell me if you find problems.
